version: '3'
services:
  web:
    build: ./python
    ports:
      - '5000:5000'
  nginx:
    image: nginx:v1
    ports:
      - '9091:80'
    volumes:
      - ./nginx/log:/var/log/nginx/
      - ./nginx/conf:/etc/nginx/nginx.conf

  node:
    build: ./node
    ports:
      - 3001:3000

  redis:
    image: 'redis:alpine'
